create database Biblioteca;
use Biblioteca;

CREATE TABLE LIVROS (
ID_LIVROS INT PRIMARY KEY auto_increment,
TITULO VARCHAR(255) NOT NULL,
AUTOR VARCHAR(255) NOT NULL,
ANO_PUBLICACAO INT NOT NULL,
GENERO VARCHAR(100) NOT NULL,
DISPONIBILIDADE BOOLEAN NOT NULL
);

CREATE TABLE USUARIOS(
ID_USUARIO INT PRIMARY KEY auto_increment,
NOME VARCHAR(255) NOT NULL,
EMAIL VARCHAR(200) NOT NULL,
TELEFONE VARCHAR(20) NOT NULL,
ENDERECO VARCHAR(200) NOT NULL
);

CREATE TABLE EMPRESTIMOS(
ID_ALUGUEL INT PRIMARY KEY auto_increment,
ID_LIVROS INT NOT NULL,
ID_USUARIOS INT NOT NULL,
DATA_EMPRESTIMO DATE NOT NULL,
DATA_DEVOLUCAO DATE NOT NULL,
FOREIGN KEY (ID_LIVROS) REFERENCES LIVROS(ID_LIVROS),
FOREIGN KEY (ID_USUARIOS) REFERENCES USUARIOS(ID_USUARIO)
);

#TIRANDO O NOT NULL DO DATA_DEVOLUCAO
ALTER TABLE EMPRESTIMOS
MODIFY COLUMN DATA_DEVOLUCAO DATE;

INSERT INTO LIVROS(TITULO, AUTOR, ANO_PUBLICACAO, GENERO, DISPONIBILIDADE)
VALUES('O Alquimista', 'Paulo Coelho', 1988, 'Ficção', TRUE),
('1984', 'George Orwell', 1949, 'Distopia', TRUE),
('Dom Casmurro', 'Machado de Assis', 1899, 'Romance', TRUE),
('A Revolução dos Bichos', 'George Orwell', 1945, 'Fábula', TRUE),
('Memórias Póstumas de Brás Cubas', 'Machado de Assis', 1881, 'Romance', TRUE),
('O Hobbit', 'J.R.R. Tolkien', 1937, 'Fantasia', TRUE),
('A Menina que Roubava Livros', 'Markus Zusak', 2005, 'Ficção Histórica', TRUE),
('Harry Potter e a Pedra Filosofal', 'J.K. Rowling', 1997, 'Fantasia', TRUE),
('Senhora', 'José de Alencar', 1875, 'Romance', TRUE),
('O Pequeno Príncipe', 'Antoine de Saint-Exupéry', 1943, 'Fábula', TRUE);

INSERT INTO USUARIOS(NOME, EMAIL, TELEFONE, ENDERECO)
VALUES('João Silva', 'joao.silva@gmail.com', '123456789', 'Rua Campos Salles, 123, Santos'),
('Maria Oliveira', 'maria.oliveira@gmail.com', '987654321', 'Avenida Siqueira, 456, São Vicente'),
('Carlos Pereira', 'carlos.pereira@gmail.com', '555666777', 'Rua Evaristo, 789, Santos'),
('Ana Santos', 'ana.santos@gmail.com', '444555666', 'Avenida Kennedy, 101, Praia Grande'),
('Pedro Almeida', 'pedro.almeida@gmail.com', '333444555', 'Rua Isabel, 202, Praia Grande');

INSERT INTO EMPRESTIMOS(ID_LIVROS, ID_USUARIOS, DATA_EMPRESTIMO, DATA_DEVOLUCAO)
VALUES(1, 1, '2024-06-01', NULL),
(2, 2, '2024-06-02', '2024-06-06'),
(3, 1, '2024-06-03', NULL),
(4, 3, '2024-06-04', '2024-06-11'),
(5, 2, '2024-06-05', NULL),
(6, 4, '2024-06-06', '2024-06-13'),
(7, 5, '2024-06-07', NULL),
(8, 3, '2024-06-08', '2024-06-14'),
(9, 4, '2024-06-09', NULL),
(10, 5, '2024-06-10', '2024-06-20');

#SELECIONANDO EMPRESTIMOS DE UM DETERMINADO USUARIO
SELECT ID_ALUGUEL, ID_LIVROS, ID_USUARIOS
FROM EMPRESTIMOS
WHERE ID_USUARIOS = 1;

#USANDO O JOIN PARA VER O NOME DO USUARIO E O NOME DO LIVRO ALUGADO
SELECT E.ID_ALUGUEL, U.NOME, L.TITULO, E.DATA_EMPRESTIMO, E.DATA_DEVOLUCAO
FROM EMPRESTIMOS E
INNER JOIN USUARIOS U ON E.ID_USUARIOS = U.ID_USUARIO
INNER JOIN LIVROS L ON E.ID_LIVROS = L.ID_LIVROS;

#Registrando um novo emprestimo para um usuario
INSERT INTO EMPRESTIMOS(ID_LIVROS, ID_USUARIOS, DATA_EMPRESTIMO)
VALUES(6, 1, '2024-06-16');
INSERT INTO EMPRESTIMOS(ID_LIVROS, ID_USUARIOS, DATA_EMPRESTIMO)
VALUES(8, 5, '2024-06-16');

#ALTERANDO A DISPONIBILIDADE DO LIVRO PARA FALSO
UPDATE LIVROS SET DISPONIBILIDADE = FALSE WHERE ID_LIVROS = 8;
UPDATE LIVROS SET DISPONIBILIDADE = FALSE WHERE ID_LIVROS = 6;

#REGISTRANDO UMA DEVOLUÇÃO
UPDATE EMPRESTIMOS SET DATA_DEVOLUCAO = '2024-06-16' WHERE ID_LIVROS = 1;
UPDATE LIVROS SET DISPONIBILIDADE = TRUE WHERE ID_LIVROS = 1;
#SELECT * FROM EMPRESTIMOS